### ISSUE TITLE
Program Output Oddities 

### ISSUE THREAD

**Issue by kircat-concatenation** [Scattercatt/MandelbrotRevamped#2]
When run, the program creates two directories in the jar file directory named:
C:\Users\{username}\Documents\MandelbrotRevamped\
C:\Users\{username}\Documents\MandelbrotRevamped\Render\

and creates two dat files named:
C:\Users\{username}\Documents\MandelbrotRevamped\data.dat
C:\Users\{username}\Documents\MandelbrotRevamped\palettes.dat

Neither the render output or dat files are stored in their proper directories, but the directory of the jar file.

 
*Using OpenJDK 17.03
*Running on Fedora 36

**Comment by Scattercatt** [comment]
Added Linux support. Issue fixed.
